# Training config

seed: 42

log: True

model_config:
  in_dims: 1
  out_dims: 1
  kernel_size: 3
  activation: 'leaky'
  alpha: 0.1

audio_dir: '/Users/inigoparra/Desktop/Datasets/speech'
original_sr: 44100
target_resample: 16000
sample_len: 64000

spectrogram_config:
  sample_rate: 16000
  n_fft: 256
  hop_length: 64
  n_mels: 64
  f_min: 80
  f_max: 8000
  norm: 'slaney'
  mel_scale: 'slaney'
  pad_mode: 'reflect'

mask_size: 50
epochs: 500
batch_size: 32
lr: 0.001
beta_1: 0.90
beta_2: 0.99
weight_decay: 0.01
save_epochs: 5

save_path: '/Users/inigoparra/Desktop/VisMAE'
save_epochs: 20
